spring:
  application:
    name: telegram-bot

  main:
    web-application-type: none

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

telegram:
  bot:
    token: ${BOT_TOKEN}
    username: ${BOT_USERNAME}